[tool.pyright]  
venvPath = "/Users/macar/personal/miniconda3/envs"
venv = "cnn"
include = ["src"]
pythonVersion = 3.12
autoSearchPaths = true
reportArgumentType = false
reportOptionalOperand = false
reportOptionalMemberAccess = false
reportPossiblyUnboundVariable = false
