# Data
dataset: mnist

# Model
model:
  model_name: resnet18
  config:
    weights: DEFAULT

# Training
batch_size: 32
num_workers: 4
num_epochs: 50
learning_rate: 0.0001
weight_decay: 0.0001
group_lasso_coef: null
cil: false
contrastive: false
rde: true
scheduler_factor: 0.1
scheduler_patience: 5

early_stop: 5

output_path: ../logs/resnet18_MNIST_RDE/
