# Data
dataset: cifar10

# Model
model:
  model_name: selfexpressivecnn
  in_ch: 3
  out_dim: 256

# Training
batch_size: 512
num_workers: 8
num_epochs: 200
learning_rate: 0.0001
weight_decay:  0.00005
orthogonal_regularization: null
metrics: []
  # - accuracy
  # - homogeneity_score
  # - completeness_score

criterion_args:
  # cross_entropy_loss: {weight: 1.0}

  self_expressive_loss:
    weight: 1.0
    args:
      beta: 0.1
      kappa: 64

  # completenesss_homogeneity_loss: 
  #   weight: 1.0
  #   args:
  #     temperature: 0.3
  #     lambda_h: 1.0
  #     lambda_c: 1.0
  #     lambda_e: 0.1

scheduler_args:
  factor: 0.1
  patience: 4

early_stop: 8

output_path: ../logs/temp/
