# Data
dataset: cifar10

# Model
model:
  model_name: classificationcnn
  in_ch: 3
  out_dim: 256
  num_layers: 1
  attention: SAM

# Training
batch_size: 32
num_workers: 8
num_epochs: 200
learning_rate: 0.001
weight_decay: 0.005
metrics:
  - accuracy
  - homogeneity_score
  - completeness_score
  - maximal_coding_rate

criterion_args:
  completeness_loss: {weight: 1.0}
  # homogeneity_loss: {weight: 0.5}

scheduler_args:
  factor: 0.1
  patience: 4

early_stop: 8

output_path: ../logs/classificationcnn_N1_CIFAR10_SAM_CL_HL/
