# Data
dataset: cifar10

# Model
model:
  model_name: resnet18l4


# Training
batch_size: 64
num_workers: 0
num_epochs: 50
learning_rate: 0.001
weight_decay: 0.005
metrics:
  - accuracy
  - homogeneity_score
  - completeness_score

criterion_args:
  cross_entropy_loss: {}

scheduler_args:
  factor: 0.1
  patience: 4

early_stop: 8

output_path: ../logs/resnet18l4_CIFAR10/
