# Data
data_root: ../data/

# Model
model_name: resnet18
model_weights: DEFAULT

# Training
batch_size: 32
num_workers: 4
num_epochs: 50
learning_rate: 0.1
weight_decay: 0.001
scheduler_gamma: 0.7
scheduler_step_size: 1

early_stop: 6

output_path: ../logs/resnet18_run3
