# Data
data_root: ../data/

# Model
model_config:
  features:
    - ["C", 1, 32, 5, 2, 0]
    - ["C", 32, 64, 3, 1, 0]
    - ["C", 64, 128, 3, 1, 0]
    - ["C", 128, 256, 3, 1, 0]
    - ["C", 256, 512, 3, 1, 0]
  pool: ["A", 1]
  classifier: [512, 10]

# Training
batch_size: 32
num_workers: 4
num_epochs: 100
learning_rate: 0.0001
weight_decay: 0.0001
group_lasso_coef: 0.1
scheduler_gamma: 0.7
scheduler_step_size: 1

early_stop: 6

output_path: ../logs/customnet_run1
