# Data
dataset: mnist
data_root: ../data/

# Model
model:
  model_name: ConvNet
  config:
    features:
      - ["C", 1, 8, 5, 2, 0]
      - ["C", 8, 16, 3, 1, 0]
      - ["C", 16, 32, 3, 1, 0]
      - ["C", 32, 64, 3, 1, 0]
      - ["C", 64, 64, 3, 1, 0]
    pool: ["A", 1]
    classifier: [64, 10]

# Training
batch_size: 32
num_workers: 4
num_epochs: 50
learning_rate: 0.0001
weight_decay: 0.0001
group_lasso_coef: null
scheduler_factor: 0.1
scheduler_patience: 5

early_stop: 8

output_path: ../logs/customnet_lasso_run1
