# Data
dataset: mnist

# Model
model:
  model_name: smallnet # resnet18ctrl
  in_ch: 1
  num_filters: 32
  kernel_size: 7
  stride: 3
  padding: 1
  attention: SAM

# Training
batch_size: 128
num_workers: 8
num_epochs: 100
learning_rate: 0.01
weight_decay: 0.005
measure_accuracy: false
criterion_args:
  # cross_entropy_loss: {weight: 1.0}
  # cluster_inducing_loss: {weight: 0.5}
  calinski_harabasz_index: {weight: 1.0}
  # maximal_coding_rate_reduction: {
  #   weight: 1.0,
  #   args: {
  #     gam1: 20,
  #     gam2: 15,
  #     eps: 0.5,
  #   }
  # }
scheduler_factor: 0.1
scheduler_patience: 3

early_stop: 6

output_path: ../logs/smallnet_MNIST_SAM_CHI/
