# Data
data_root: ../data/

# Model
model_config:
  features:
    - ["C", 1, 64, 7, 3, 2]
    - ["M", 3, 2, 0, 1]
    - ["C", 64, 128, 5, 1, 2]
    - ["C", 128, 256, 3, 1, 1]
    - ["M", 2, 1, 0, 1]
    - ["C", 256, 512, 3, 1, 1]
    - ["A", 3, 3, 0]
  # pool: ["A", 1]
  classifier: [512, 10]

# Training
batch_size: 32
num_workers: 4
num_epochs: 100
learning_rate: 0.001
weight_decay: 0.0001
group_lasso_coef: 0.1
scheduler_gamma: 0.7
scheduler_step_size: 1

early_stop: 6

output_path: ../logs/resnet18_run5
