# Data
dataset: cifar10

# Model
model:
  model_name: clustercnn
  in_ch: 3
  out_dim: 256
  num_layers: 1
  attention: SAM

# Training
batch_size: 128
num_workers: 8
num_epochs: 200
learning_rate: 0.001
weight_decay: 0.005
metrics:
  - accuracy
  - completeness_score
  - homogeneity_score

criterion_args:
  completeness_loss: {weight: 0.5}
  homogeneity_loss: {weight: 0.5}

scheduler_args:
  factor: 0.1
  patience: 4

early_stop: 8

output_path: ../logs/customnet_CIFAR10_SAM_CHI/
